name: Branch CI
on:
  push:
    branches:
      - '**'      # matches every branch
      - '!main'   # excludes main

jobs:
  Testing:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_db_name: ${{ secrets.TF_VAR_db_name }}
      TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
    steps:
    - uses: actions/checkout@v3
    - name: Setting up terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6
    - name: Terraform init
      run: terraform init
    - name: Terraform validate
      run: terraform validate -no-color
    - name: Terraform plan
      run: terraform plan


